[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
alloy = { version = "1.1.3", features = ["full"] }
tokio = { version = "1.48.0", features = ["full"] }
# logging
log = "0.4"
fern = { version = "0.7", features = ["colored"] }
chrono = "0.4.42"
